apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-ip-whitelist-route
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: ip-whitelist-traffic
    priority: 200  # En yüksek priority - IP whitelist
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: X-Forwarded-For
        op: In
        values:
        - "192.168.1.100"
        - "192.168.1.101"
        - "10.0.0.50"
        - "172.16.0.25"
    backends:
    - serviceName: portal-svc-bot
      servicePort: 80
    plugins:
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-bot-route
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: bot-traffic
    priority: 100  # Bot trafiği için
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: User-Agent
        op: Equal
        value: "Bot"
    backends:
    - serviceName: portal-svc-bot
      servicePort: 80
    plugins:
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-normal-route
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: normal-traffic
    priority: 30  # Normal kullanıcılar için düşük priority
    match:
      hosts:
      - "*"
      paths:
      - "/*"
    backends:
    - serviceName: portal-svc
      servicePort: 80
    plugins:
    - name: limit-count
      enable: true
      config:
        count: 10
        time_window: 60
        key: "remote_addr"
        rejected_code: 429