apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-bot-app
  labels:
    app: portal-bot-app
spec:
  replicas: 2 # 4 node cluster'da 2 replica
  selector:
    matchLabels:
      app: portal-bot-app
  template:
    metadata:
      labels:
        app: portal-bot-app
    spec:
      containers:
      - name: portal-bot
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: portal-bot-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-bot-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Portal - Bot Users</title></head>
    <body style="background-color: #ffe8e8; padding: 20px; font-family: Arial;">
        <h1>🤖 Portal Bot Sayfası</h1>
        <p>Bot trafiği için özel sayfa</p>
        <p><strong>Node:</strong> <script>document.write(window.location.hostname)</script></p>
        <p><strong>Timestamp:</strong> <script>document.write(new Date())</script></p>
        <p><strong>Rate Limit:</strong> 2 req/saniye (Bot için düşük)</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: portal-svc-bot
spec:
  selector:
    app: portal-bot-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP