apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-app
  labels:
    app: portal-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-app
  template:
    metadata:
      labels:
        app: portal-app
    spec:
      containers:
      - name: portal
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: portal-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Portal - Normal Users</title></head>
    <body style="background-color: #e8f5e8; padding: 20px; font-family: Arial;">
        <h1>🌟 Portal Ana Sayfa</h1>
        <p>Hoşgeldiniz! Bu normal kullanıcılar için portal sayfası.</p>
        <p><strong>Node:</strong> <script>document.write(window.location.hostname)</script></p>
        <p><strong>Timestamp:</strong> <script>document.write(new Date())</script></p>
        <p><strong>Rate Limit:</strong> 50 req/saniye</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: portal-svc
spec:
  selector:
    app: portal-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP