apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-jwt-routing
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: jwt-admin-users
    priority: 80  # JWT ile admin kullanıcılar normal'e
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: X-User-Role
        op: In
        values:
        - "admin"
        - "super_admin"
        - "root"
    backends:
    - serviceName: portal-svc
      servicePort: 80
    plugins:
    - name: limit-count
      enable: true
      config:
        count: 10
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
  - name: jwt-bot-user-traffic
    priority: 170  # JWT bot kullanıcıları için
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: X-User-Type
        op: In
        values:
        - "bot_user"
        - "crawler"
        - "scraper"
    backends:
    - serviceName: portal-svc-bot
      servicePort: 80
    plugins:
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-username-routing
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: username-routing
    priority: 70  # Username routing bot'a
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: X-Username
        op: In
        values:
        - "testuser"
        - "admin_user"
        - "bot_user"
    backends:
    - serviceName: portal-svc-bot
      servicePort: 80
    plugins:
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
