apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-jwt-admin-route
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: jwt-admin-users
    priority: 60  # JWT ile admin kullanıcılar normal'e
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: Authorization
        op: RegexMatch
        value: "Bearer.*"
    backends:
    - serviceName: portal-svc
      servicePort: 80
    plugins:
    - name: jwt-auth
      enable: true
      config:
        header: "authorization"
        query: "jwt"
        cookie: "jwt"
        key_claim_name: "key"
        hide_credentials: false
    - name: limit-count
      enable: true
      config:
        count: 10
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-jwt-bot-route
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: jwt-bot-user-traffic
    priority: 90  # JWT bot kullanıcıları için
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: Authorization
        op: RegexMatch
        value: "Bearer.*"
    backends:
    - serviceName: portal-svc-bot
      servicePort: 80
    plugins:
    - name: jwt-auth
      enable: true
      config:
        header: "authorization"
        query: "jwt"
        cookie: "jwt"
        key_claim_name: "key"
        hide_credentials: false
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: portal-username-routing
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  http:
  - name: username-routing
    priority: 40  # Username routing bot'a
    match:
      hosts:
      - "*"
      paths:
      - "/*"
      exprs:
      - subject:
          scope: Header
          name: X-Username
        op: In
        values:
        - "testuser"
        - "admin_user"
        - "bot_user"
    backends:
    - serviceName: portal-svc-bot
      servicePort: 80
    plugins:
    - name: limit-count
      enable: true
      config:
        count: 2
        time_window: 60
        key: "remote_addr"
        rejected_code: 429
